# Generated by Django 2.1 on 2018-10-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180823_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='DiaryPost',
        ),
    ]
